const arrayOfAnecdote = [
  "The Eiffel Tower should be called the Nouguier and Koechlin Tower. \nIn fact, Koechlin and Nouguier, two engineers of the workshops of Gustave Eiffel had the idea of ​​the Iron Lady to shine during the universal exhibition of 1889, Eiffel was initially completely disinterested of the project. \nHe had the good idea to buy the patent to present himself the famous construction which was finally given his name! ",
  "There is only one stop sign in the whole city. \nThe lucky winner is quai St Exupéry. Apart from this place, the right-of-priority rule applies to the rest of the city.",
  "You have to pay € 200,000 to be a taxi driver in Paris. \nIf you've been to Paris before, you may have noticed that taxis are almost impossible to find. On Saturday nights, it is very common to see dozens of people on the sidewalk waiting for or fighting for a taxi. \nAnd it comes from the \"simple\" fact that taxi drivers have to pay the small sum of ... 200 000 € to get a license. We understand a little better why they are not a fan of services like Uber!",
  "Pont Neuf is the oldest bridge in Paris. Paradoxically, the Pont Neuf is the oldest bridge in the capital. \nIn the early 17th, it was named as it since it was very new to have a real sidewalk contrary to the old bridges in Paris, thus avoiding pedestrians from walking in horse dung.",
  "The famous Pont des Amours no longer exists. In fact, the bridge is still there, but all padlocks have been removed for security reasons. \nIndeed, with about 1 million padlocks, representing a weight of 45 tons, they began to seriously damage the structure of the bridge. \nThe City of Paris was strongly criticized for taking the decision to remove emblematic padlocks, considered by most Parisians (and tourists!) s a cultural heritage and as one of the main symbols of the city.",
  "The term \"chicken\" to designate a policeman was born in Paris! After the police buildings caught fire, the Prefecture of Police settled on the L’’île de la Cité, in premises made available by Jules Ferry. These premises having been built on the former site where was held the poultry market of the capital, it was not long before we call the police officers ... \"chickens\"!",
  "The Eiffel Tower is NOT the most visited monument in Paris. \nIn 2014, the Eiffel Tower was only the fourth most visited site in the French capital. It is the Notre-Dame de Paris cathedral that comes first.",
  "The main bell of the Notre-Dame cathedral weighs 13 tons. Or more than the weight of 3 elephants. The inner part of the bell alone weighs 500 kg. \nThe bell rings for major Catholic holidays such as Christmas, Easter, Pentecost, etc., or for other important events such as the death of Pope John Paul II and the election of his successor Benedict XVI. \nOh, and the biggest bell has a name: Emmanuel.",
  "Ghost subway stations are hiding under Paris soil. \nAnd not just one ... 14 ghost metro stations are hidden in the basement of the capital. Most of them were closed at the beginning of the Second World War, while a large part of the personnel had been mobilized for the war. \nSome are then reopened temporarily, then permanently abandoned, being too close to other stations. This is the case, for example, of the St Martin station, located 100m from Strasbourg-St Denis. \nIt is one of the largest abandoned resorts in the capital, regularly visited by urban explorers ...",
  "Place de la Concorde is one of the largest sundials in the world. \nMost Parisians themselves do not know, but the Place de la Concorde is a giant sundial. The Obelisk (the main monument of the square, an Egyptian column 23 meters high) can read the approximate time depending on its shadow, depending on the position of the sun. \nIf you pay attention while walking around the Place de la Concorde, you will even notice some markers of the hour in Roman numerals on the pavement."
];

module.exports = arrayOfAnecdote;
